---
name: Tomas
surname: Quezada
position: "Entomology Technician"
address: "Cornell University"
phone: +1 956-286-1840
# www: mariecurie.com
email: "TAQ3@cornell.edu"
# twitter: mariecurie
github: https://github.com/taq42408
# linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---
```{r functions}
readExcelSheets <- function(filename){
  # read all sheets in .xlsx 
  all <- readxl::excel_sheets(filename)
  
  # import each sheet into a list using readxl::read_excel
  list <- lapply(all, function(x) readxl::read_excel(filename, sheet = x))
  
  # save sheet name for each sheet (list)
  names(list) <- all
  
  # breaks up list and creates a dataframe for each sheet with df names matching sheet names
  list2env(list, envir = .GlobalEnv)
}
```

```{r load data, include=FALSE}
# appointments <- read_csv(here("data", "appointments.csv"))
# education <- read_csv(here("data", "education.csv"))
# research <- read_csv(here("data", "research_experience.csv"))
# teaching <- read_csv(here("data", "teaching_supervision.csv"))
# awards <- read_csv(here("data", "awards.csv"))
# leadership <- read_csv(here("data", "leadership.csv"))
# presentations <- read_csv(here("data", "presentations.csv"))
# training <- read_csv(here("data", "training.csv"))
# skills <- read_csv(here("data", "skills_table.csv"))
# tools <- read_csv(here("data", "digital_tools.csv"))
readExcelSheets(here::here("data", "cv_data.xlsx"))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

